import numpy as np
import pytest

from src.config import CLASSES
from src.models.amc_cnn import AMC_CNN
from src.timeline import detections
from src.ui.session import (CaptureSession, analyze, load_scenario,
                             load_test_example, load_upload)


@pytest.fixture(scope="module")
def model():
    m = AMC_CNN(num_classes=len(CLASSES), input_len=512)
    m.eval()
    return m


def test_load_scenario_returns_a_session_with_truth(model):
    s = load_scenario(model, total_duration=0.01, hop=256, seed=0)
    assert isinstance(s, CaptureSession)
    assert s.source == "scenario"
    assert s.truth is not None and len(s.truth) > 0
    assert s.snr_known is True


def test_scenario_session_result_covers_the_capture(model):
    s = load_scenario(model, total_duration=0.01, hop=256, seed=0)
    assert s.result.n_windows == 1 + (32_000 - 512) // 256


def test_upload_session_has_no_truth_and_unknown_snr(model):
    iq = np.random.randn(4096) + 1j * np.random.randn(4096)
    s = analyze(iq, model, source="upload", hop=256)
    assert s.truth is None
    assert s.snr_known is False


def test_truth_is_never_present_for_a_non_scenario_source(model):
    """Provenance rule: TRUTH elements must not exist unless the capture was
    generated by us."""
    iq = np.random.randn(2048) + 1j * np.random.randn(2048)
    for source in ("upload", "test-example"):
        assert analyze(iq, model, source=source, hop=512).truth is None


def test_session_stores_the_raw_unnormalized_capture(model):
    """The waterfall and SNR estimate depend on real amplitude surviving."""
    iq = (np.random.randn(2048) + 1j * np.random.randn(2048)) * 50.0
    s = analyze(iq, model, source="upload", hop=512)
    assert np.mean(np.abs(s.iq) ** 2) > 100.0


def test_detected_events_use_per_class_thresholds(model):
    """The session must not fall back to a flat 0.5 -- that is the bug this
    work fixes."""
    s = load_scenario(model, total_duration=0.005, hop=512, seed=0)
    assert s.thresholds["LFM_RADAR"] == pytest.approx(0.26)
    assert s.thresholds["JAMMING"] == pytest.approx(0.77)


def test_window_count_cap_is_enforced(model):
    with pytest.raises(ValueError, match="too many windows"):
        analyze(np.zeros(3_000_000, dtype=complex), model, source="upload",
                hop=64, max_windows=4000)


def test_uploads_analyze_the_whole_file_not_just_the_first_window(model, tmp_path):
    """The old UI did iq[:512] and silently dropped everything after 160 us."""
    n = 8192
    raw = np.empty(n * 2, dtype=np.float32)
    raw[0::2] = np.random.randn(n)
    raw[1::2] = np.random.randn(n)
    path = tmp_path / "capture.f32"
    raw.tofile(path)
    s = load_upload(str(path), model, hop=256)
    assert len(s.iq) == n
    assert s.result.n_windows == 1 + (n - 512) // 256


def test_upload_rejects_a_file_with_no_samples(model, tmp_path):
    path = tmp_path / "empty.f32"
    np.array([], dtype=np.float32).tofile(path)
    with pytest.raises(ValueError, match="no complex samples"):
        load_upload(str(path), model, hop=256)


def test_context_1_single_test_example_is_exactly_one_window(model):
    """512 samples -> 1 window, no timeline. Signal Analysis must still work
    in this degenerate case."""
    X = np.random.randn(1, 2, 512).astype(np.float32)
    y = np.zeros((1, 8), dtype=np.float32)
    s = load_test_example(model, X, y, np.array([-6.0]), 0)
    assert s.result.n_windows == 1
    assert s.source == "test-example"
    assert s.snr_known is True
    assert s.true_snr_db == pytest.approx(-6.0)
    assert s.truth is None


def test_context_2_capture_has_a_timeline(model):
    s = load_scenario(model, total_duration=0.01, hop=256, seed=0)
    assert s.result.n_windows > 1
    assert s.result.times_us[1] > s.result.times_us[0]


def test_context_3_two_classes_produce_one_combined_event(model):
    """FHSS 0.90 + JAMMING 0.85 -> both detected -> ONE event."""
    from dataclasses import replace
    s = load_scenario(model, total_duration=0.005, hop=512, seed=0)
    probs = np.zeros((4, 8), dtype=np.float32)
    probs[:, CLASSES.index("FHSS")] = 0.90
    probs[:, CLASSES.index("JAMMING")] = 0.85
    forced = replace(s.result, probs=probs, starts=np.arange(4) * 512)
    events = detections(forced, s.thresholds)
    assert len(events) == 1
    assert set(events[0].classes) == {"FHSS", "JAMMING"}


def test_context_4_display_rules_never_mutate_the_raw_result(model):
    """THE key isolation test: the raw per-window probabilities the scorecard
    would use must be identical before and after the display layer runs."""
    s = load_scenario(model, total_duration=0.01, hop=256, seed=0)
    raw_before = s.result.probs.copy()
    s.events(smoothed=True)
    s.tiers(smoothed=True)
    s.judged_events(smoothed=True)
    np.testing.assert_array_equal(s.result.probs, raw_before)


def test_raw_mode_bypasses_the_display_rules(model):
    """Raw mode must show what the model actually did, so the gate and hold
    are off there."""
    s = load_scenario(model, total_duration=0.02, hop=256, seed=0)
    assert len(s.events(smoothed=False)) >= len(s.events(smoothed=True))


def test_alerts_never_include_noise_floor(model):
    s = load_scenario(model, total_duration=0.02, hop=256, seed=0)
    for e in s.judged_events():
        assert "NOISE_FLOOR" not in e.classes


def test_scorecard_path_never_imports_smoothing():
    """src/evaluate.py must not reach for the display-only transforms."""
    import inspect

    import src.evaluate as ev
    source = inspect.getsource(ev)
    for banned in ("smooth(", "noise_gate", "hold_us"):
        assert banned not in source, (
            f"src/evaluate.py references {banned!r} -- benchmark numbers must "
            "stay per-window, ungated and unsmoothed"
        )
