import numpy as np
import torch
import pytest

from src.config import CLASSES
from src.models.amc_cnn import AMC_CNN
from src.timeline import detections
from src.ui.session import (CaptureSession, analyze, load_scenario,
                             load_test_example, load_upload)


@pytest.fixture(scope="module")
def model():
    """Untrained model, but with FIXED weights.

    AMC_CNN initialises randomly, so without a seed every test in this file
    that runs the model gets different predictions on every run -- which made
    assertions about event counts flaky, failing roughly one run in three for
    no reason connected to the code under test.
    """
    torch.manual_seed(0)
    m = AMC_CNN(num_classes=len(CLASSES), input_len=512)
    m.eval()
    return m


def test_load_scenario_returns_a_session_with_truth(model):
    s = load_scenario(model, total_duration=0.01, hop=256, seed=0)
    assert isinstance(s, CaptureSession)
    assert s.source == "scenario"
    assert s.truth is not None and len(s.truth) > 0
    assert s.snr_known is True


def test_scenario_session_result_covers_the_capture(model):
    s = load_scenario(model, total_duration=0.01, hop=256, seed=0)
    assert s.result.n_windows == 1 + (32_000 - 512) // 256


def test_upload_session_has_no_truth_and_unknown_snr(model):
    iq = np.random.randn(4096) + 1j * np.random.randn(4096)
    s = analyze(iq, model, source="upload", hop=256)
    assert s.truth is None
    assert s.snr_known is False


def test_truth_is_never_present_for_a_non_scenario_source(model):
    """Provenance rule: TRUTH elements must not exist unless the capture was
    generated by us."""
    iq = np.random.randn(2048) + 1j * np.random.randn(2048)
    for source in ("upload", "test-example"):
        assert analyze(iq, model, source=source, hop=512).truth is None


def test_session_stores_the_raw_unnormalized_capture(model):
    """The waterfall and SNR estimate depend on real amplitude surviving."""
    iq = (np.random.randn(2048) + 1j * np.random.randn(2048)) * 50.0
    s = analyze(iq, model, source="upload", hop=512)
    assert np.mean(np.abs(s.iq) ** 2) > 100.0


def test_detected_events_use_per_class_thresholds(model):
    """The session must not fall back to a flat 0.5 -- that is the bug this
    work fixes."""
    s = load_scenario(model, total_duration=0.005, hop=512, seed=0)
    assert s.thresholds["LFM_RADAR"] == pytest.approx(0.26)
    assert s.thresholds["JAMMING"] == pytest.approx(0.77)


def test_window_count_cap_is_enforced(model):
    with pytest.raises(ValueError, match="too many windows"):
        analyze(np.zeros(3_000_000, dtype=complex), model, source="upload",
                hop=64, max_windows=4000)


def test_uploads_analyze_the_whole_file_not_just_the_first_window(model, tmp_path):
    """The old UI did iq[:512] and silently dropped everything after 160 us."""
    n = 8192
    raw = np.empty(n * 2, dtype=np.float32)
    raw[0::2] = np.random.randn(n)
    raw[1::2] = np.random.randn(n)
    path = tmp_path / "capture.f32"
    raw.tofile(path)
    s = load_upload(str(path), model, hop=256)
    assert len(s.iq) == n
    assert s.result.n_windows == 1 + (n - 512) // 256


def test_upload_rejects_a_file_with_no_samples(model, tmp_path):
    path = tmp_path / "empty.f32"
    np.array([], dtype=np.float32).tofile(path)
    with pytest.raises(ValueError, match="no complex samples"):
        load_upload(str(path), model, hop=256)


def test_context_1_single_test_example_is_exactly_one_window(model):
    """512 samples -> 1 window, no timeline. Signal Analysis must still work
    in this degenerate case."""
    X = np.random.randn(1, 2, 512).astype(np.float32)
    y = np.zeros((1, 8), dtype=np.float32)
    s = load_test_example(model, X, y, np.array([-6.0]), 0)
    assert s.result.n_windows == 1
    assert s.source == "test-example"
    assert s.snr_known is True
    assert s.true_snr_db == pytest.approx(-6.0)
    assert s.truth is None


def test_context_2_capture_has_a_timeline(model):
    s = load_scenario(model, total_duration=0.01, hop=256, seed=0)
    assert s.result.n_windows > 1
    assert s.result.times_us[1] > s.result.times_us[0]


def test_context_3_two_classes_produce_one_combined_event(model):
    """FHSS 0.90 + JAMMING 0.85 -> both detected -> ONE event."""
    from dataclasses import replace
    s = load_scenario(model, total_duration=0.005, hop=512, seed=0)
    probs = np.zeros((4, 8), dtype=np.float32)
    probs[:, CLASSES.index("FHSS")] = 0.90
    probs[:, CLASSES.index("JAMMING")] = 0.85
    forced = replace(s.result, probs=probs, starts=np.arange(4) * 512)
    events = detections(forced, s.thresholds)
    assert len(events) == 1
    assert set(events[0].classes) == {"FHSS", "JAMMING"}


def test_context_4_display_rules_never_mutate_the_raw_result(model):
    """THE key isolation test: the raw per-window probabilities the scorecard
    would use must be identical before and after the display layer runs."""
    s = load_scenario(model, total_duration=0.01, hop=256, seed=0)
    raw_before = s.result.probs.copy()
    s.events(smoothed=True)
    s.tiers(smoothed=True)
    s.judged_events(smoothed=True)
    np.testing.assert_array_equal(s.result.probs, raw_before)


def test_raw_mode_bypasses_the_display_rules(model):
    """Raw mode must show what the model actually did, so the gate and hold
    are off there.

    Asserted on the RULES rather than on event counts. Counts depend on the
    model's predictions, and an untrained model's are arbitrary -- the earlier
    version compared raw vs smoothed counts and failed about one run in three.
    What matters is that raw mode passes no gate and no hold.
    """
    s = load_scenario(model, total_duration=0.02, hop=256, seed=0)
    assert s._rules(smoothed=False) == {"noise_gate": None, "hold_us": 0.0}
    assert s._rules(smoothed=True) == {"noise_gate": s.noise_gate,
                                        "hold_us": s.hold_us}


def test_alerts_never_include_noise_floor(model):
    s = load_scenario(model, total_duration=0.02, hop=256, seed=0)
    for e in s.judged_events():
        assert "NOISE_FLOOR" not in e.classes


def test_scorecard_path_never_imports_smoothing():
    """src/evaluate.py must not reach for the display-only transforms."""
    import inspect

    import src.evaluate as ev
    source = inspect.getsource(ev)
    for banned in ("smooth(", "noise_gate", "hold_us"):
        assert banned not in source, (
            f"src/evaluate.py references {banned!r} -- benchmark numbers must "
            "stay per-window, ungated and unsmoothed"
        )


class _StubSession:
    """Minimal stand-in for CaptureSession.

    _channel_state only asks for tiers, and testing it through a real model
    would make the assertion depend on that model's predictions -- which, for
    the untrained fixture in this file, are random weights and therefore a
    different answer every run. A stub makes the formatting logic itself the
    thing under test.
    """

    def __init__(self, tiers):
        self._tiers = tiers

    def tiers(self, smoothed=True):
        return self._tiers


def test_empty_channel_is_reported_positively():
    """An empty capture must SAY so, not merely produce no emitter events.

    emitter_events() filters NOISE_FLOOR out by design, so a capture the model
    correctly reads as empty otherwise displays only whatever false positive
    survived -- showing the one wrong answer and hiding the right ones. This
    is the exact case observed on noise_floor.f32: 118 of 119 windows correct,
    and the console said "1 events: LFM_RADAR 28%".
    """
    from src.ui.pages.rf_replay import _channel_state
    state = _channel_state(_StubSession(["Empty"] * 118 + ["Military"]), True)
    assert "CHANNEL EMPTY" in state
    assert "99" in state


def test_busy_channel_is_not_announced_as_empty():
    from src.ui.pages.rf_replay import _channel_state
    tiers = ["Military"] * 60 + ["Hostile"] * 30 + ["Empty"] * 10
    state = _channel_state(_StubSession(tiers), True)
    assert "CHANNEL EMPTY" not in state
    assert "10% empty" in state


def test_channel_state_handles_an_empty_timeline():
    from src.ui.pages.rf_replay import _channel_state
    assert _channel_state(_StubSession([]), True) == ""


def test_display_mode_is_carried_on_the_session(model):
    """Every page reads the same capture, so they must read the same view.

    RF Replay owns the smoothing toggle; Overview and Alerts render from the
    same session. Before this, switching RF Replay to Raw left them on
    smoothed -- 70 events on one page and 7 on another, with nothing on screen
    explaining the difference.
    """
    s = load_scenario(model, total_duration=0.02, hop=512, seed=1,
                       case="All three")
    assert s.display_smoothed is True

    s.display_smoothed = False
    assert s.events() == s.events(smoothed=False)
    assert s.tiers() == s.tiers(smoothed=False)

    s.display_smoothed = True
    assert s.events() == s.events(smoothed=True)


def test_display_mode_survives_a_model_switch(model):
    """reanalyze() rebuilds the session for a different model; the operator's
    view choice is a property of the session, not of the model."""
    from src.ui.session import reanalyze
    s = load_scenario(model, total_duration=0.02, hop=512, seed=1,
                       case="All three")
    s.display_smoothed = False
    assert reanalyze(s, model).display_smoothed is False


def test_a_civilian_scene_reports_the_snr_it_actually_achieved(model):
    """You can add noise to a recording but never remove it, so a civilian
    scene cannot be cleaner than the library bin it was drawn from. Claiming
    the requested figure would put a number on screen that is not true of the
    capture."""
    from src.config import CFG
    s = load_scenario(model, total_duration=0.01, hop=512, snr_db=10,
                       case="Civilian only")
    assert s.snr_known is True
    assert s.true_snr_db <= max(CFG["snr_bins_db"])


def test_snr_capped_flag_set_only_when_a_civilian_request_exceeds_the_library_bin(model):
    """snr_capped tells the page the on-screen SNR number was reduced from
    what the operator actually requested. It must be True for a civilian
    scene requested above the library's cleanest bin, and False for a
    synthetic-only scene, which never touches the library at all."""
    from src.config import CFG
    cleanest = max(CFG["snr_bins_db"])
    s = load_scenario(model, total_duration=0.01, hop=512,
                       snr_db=cleanest + 20, case="Civilian only")
    assert s.snr_capped is True

    s2 = load_scenario(model, total_duration=0.01, hop=512,
                        snr_db=cleanest + 20, case="All three")
    assert s2.snr_capped is False


def test_requested_snr_db_carries_what_the_operator_actually_asked_for(model):
    """10f: the header needs both the requested and achieved SNR to say
    "capped from X dB" rather than the achieved figure alone plus a word
    ("library") that names an implementation detail. requested_snr_db must
    equal the dropdown value the operator picked, not the achieved
    true_snr_db it got capped down to -- and must stay None when nothing was
    capped, so an uncapped session's header keeps its old phrasing."""
    from src.config import CFG
    cleanest = max(CFG["snr_bins_db"])
    requested = cleanest + 20
    s = load_scenario(model, total_duration=0.01, hop=512,
                       snr_db=requested, case="Civilian only")
    assert s.snr_capped is True
    assert s.requested_snr_db == requested
    assert s.requested_snr_db != s.true_snr_db

    s2 = load_scenario(model, total_duration=0.01, hop=512,
                        snr_db=requested, case="All three")
    assert s2.snr_capped is False
    assert s2.requested_snr_db is None


def test_capped_header_says_what_was_requested_and_delivered(model):
    """The RF Replay header must say what the operator asked for AND what
    the capture actually delivered -- "capped from 20 dB" -- rather than the
    achieved figure alone dressed up with a word ("library") that names an
    implementation detail no other line in this UI uses."""
    from src.config import CFG
    from src.ui.pages.rf_replay import _render
    cleanest = max(CFG["snr_bins_db"])
    requested = cleanest + 20
    s = load_scenario(model, total_duration=0.01, hop=512,
                       snr_db=requested, case="Civilian only")
    head = _render(s, "Raw", "single")[1]
    assert f"capped from {requested:.0f} dB" in head
    assert "library" not in head.lower()
