// GENERATED by web/build.py from configs/default.yaml's
// multilabel_thresholds_per_class. Do not edit by hand -- re-run
// `python web/build.py` after scripts/calibrate_thresholds.py.
//
// These are the decision points the deployed page actually uses, so
// they must match the checkpoints in web/models/. They are generated
// because the hand-maintained copy in analysis.js drifted once.
export const THRESHOLDS = {
  "BPSK": 0.16,
  "QPSK": 0.16,
  "16QAM": 0.19,
  "64QAM": 0.2,
  "LFM_RADAR": 0.24,
  "FHSS": 0.24,
  "JAMMING": 0.89,
  "NOISE_FLOOR": 0.16,
};
